config.php
source/_layouts/camps.blade.php
source/_layouts/update.blade.php
source/_partials/update.blade.php
source/_updates/171029-ber170-ende.md
source/_updates/180211-ber1802-ende.md
source/_updates/180222-hh1803-ueberweisung.md
source/_updates/180223-due1803-ueberweisung.md
source/_updates/180223-hh1803-location.md
source/_updates/180223-koe1805-location.md

Add: Updates

---

source/initiative/partner.blade.php

Fix: Add sponors by tier to partner

---

source/_partials/footer.blade.php
source/_partials/navbar.blade.php

Added a new navbar-button for the blog.

Add link to blog in navbar

---

source/index.blade.php

The word didn't quite fit and looked unfancy.

Changed title string

---

source/_partials/testimonials.blade.php
source/index.blade.php

> #8 
> - [x] Testimonials as an own collection
> - [x] Three testimonials on `/` to collection
> - [x] Dynamic output of latest testimonials
The output of the three testimonials is not random but a random output could get implemented

Add: dynamic testimonials

---

source/_layouts/master.blade.php

Reverts CodeDesignInitiative/cdweb1801#175

Revert "Fix: move additional styles yield in styles meta"

---

composer.lock

>  #87 
> - [x] composer update
> ###### => updated 19 packages including jigsaw

Update: jigsaw => v.1.2.2 & 18 other packages

---

source/blog.blade.php

Fix: title Camps -> Blogs

---

source/_coaches/limbach.md

Cut: example coach limbach

---

source/_partials/scripts.blade.php

Cut: google analytics

---

source/_layouts/blogs.blade.php
source/_layouts/camps.blade.php
source/_layouts/master.blade.php
source/blog.blade.php
source/camps.blade.php
source/camps/coach.blade.php

Fix: styles yield problems

---

_redirects

Fix: ambassador form redirect

---

source/_layouts/camps.blade.php
source/initiative/spenden.blade.php

Fix: fonts mono -> sans

---

package-lock.json
package.json

Add command to `npm production`

Fix redirects

---

source/community/index.blade.php

The image is now responsive at the top right and it will not grow too big for larger screens.

Make image responsive in community

---

bootstrap.php
composer.json
composer.lock
config.php
listeners/GenerateSitemap.php

Added sitemap while doing it I fixed issues with the partner collection.
There was a problem with the names in the URL's.
Issues #11

Add sitemap

---

source/_layouts/camps.blade.php

Found an issue on [https://code.design/camps/berlin/1710](https://code.design/camps/berlin/1710)
Fixed the bug in this pull request and formatted the file
Old Line: 210
New Line: 124
Problem: using `or` instead of `??`

Fix partners in camps

---

source/feed.blade.rss

This adds an RSS Feed as wished in #44 
This is in all in one Feed and each camp has its own category.
So that users can easily subscribe to all camps.
What I don't know is if the description would be better as the real content and where to cut it.
Maybe this could be fixed.

Add RSS feed

---

_redirects

It is just left to add an SSL-Certificate to code.camp so that even https will be redirected
Issue #141

Add redirects from code.camp to code.design/camps

---

source/_components/person_card.blade.php

Fix Responsive Bug on /coaches

---

source/_partners/check24.md
source/_partners/meeva.md
source/_partners/porsche.md
source/_partners/qaware.md
source/_partners/sapient.md
source/_partners/startplatz.md
source/_partners/telekom.md
source/_partners/trivago.md

I don't know if all links are required, but I still added them.

Add missing partner links

---

source/_partials/footer.blade.php

Show in the footer that there are no active camps
If there are active camps show "teilnahmebedingungen"
List the 4 last camps with the last at the top
Remove commented camps
Change appearance of "last camps"-title
Fix #94 #64

Update camp-listing in footer

---

source/_camps/1811-mue.md
source/_partials/campy.blade.php
source/_partials/footer.blade.php
source/_partials/interest.blade.php
source/anfrage.blade.php
source/kontakt.blade.php
source/magazin/bestellen.blade.php
source/magazin/gewinnspiel.blade.php

return_path and error_path still need to be set.
But I didn't know where to refer them to.
Only the newsletter registration still goes over the other provider because it is a subscription list.
Fixes #366

Change forms to campy-app

---

source/assets/.gitignore

It is really annoying to have this assets folder every time in my git path.

Add source/assets/.gitignore
